[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors/#"]
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "e9_3eksp9tIAsSxGqhLCAGaL38kyKGRJEDeHFcFcfC8_xC6qSvum3jy0R_j9J6cnxhz7e25OUzfMmusDjWsO1Q=="
  organization = "my-org"
  bucket = "sensors"